"""
Token server for the Eva English Coach platform.
Generates LiveKit room tokens and serves the frontend.
"""
import os
import uuid
from datetime import timedelta
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from livekit import api

load_dotenv()

LIVEKIT_URL = os.getenv("LIVEKIT_URL")
LIVEKIT_API_KEY = os.getenv("LIVEKIT_API_KEY")
LIVEKIT_API_SECRET = os.getenv("LIVEKIT_API_SECRET")

app = FastAPI(title="Eva English Coach")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class TokenRequest(BaseModel):
    user_name: str = "Learner"
    mode: str = "passive"  # 'passive' (Collection) or 'coach' (Active Roleplay)

latest_room_name = None

@app.post("/api/token")
async def create_token(req: TokenRequest):
    """Generate a LiveKit room token for the user."""
    if not all([LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET]):
        raise HTTPException(status_code=500, detail="LiveKit credentials not configured")

    global latest_room_name
    room_name = f"eva-session-{uuid.uuid4().hex[:8]}"
    latest_room_name = room_name
    participant_identity = f"user-{uuid.uuid4().hex[:6]}"

    # Dispatch the eva-coach agent to this room
    agent_dispatch = api.RoomAgentDispatch(
        agent_name="eva-expert",
        metadata=f'{{"customer_name": "{req.user_name}", "mode": "{req.mode}"}}',
    )
    room_config = api.RoomConfiguration(
        agents=[agent_dispatch],
    )

    token = (
        api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
        .with_identity(participant_identity)
        .with_name(req.user_name)
        .with_grants(
            api.VideoGrants(
                room_join=True,
                room=room_name,
                can_publish=True,
                can_subscribe=True,
            )
        )
        .with_metadata(f'{{"customer_name": "{req.user_name}"}}')
        .with_room_config(room_config)
        .with_ttl(timedelta(hours=1))
    )

    return {
        "token": token.to_jwt(),
        "url": LIVEKIT_URL,
        "room_name": room_name,
        "identity": participant_identity,
    }


@app.get("/api/agent_viewer_token")
async def get_viewer_token():
    """Generate a passive viewer token for the currently active room."""
    global latest_room_name
    if not latest_room_name:
        raise HTTPException(status_code=404, detail="No active Eva session in progress yet.")
    
    participant_identity = f"observer-{uuid.uuid4().hex[:6]}"
    
    token = (
        api.AccessToken(LIVEKIT_API_KEY, LIVEKIT_API_SECRET)
        .with_identity(participant_identity)
        .with_name("Developer Dashboard")
        .with_grants(
            api.VideoGrants(
                room_join=True,
                room=latest_room_name,
                can_publish=False,
                can_subscribe=True,
            )
        )
        .with_ttl(timedelta(hours=1))
    )

    return {
        "token": token.to_jwt(),
        "url": LIVEKIT_URL,
        "room_name": latest_room_name,
        "identity": participant_identity,
    }


@app.get("/api/health")
async def health():
    return {"status": "ok", "agent": "Eva English Coach"}

@app.get("/api/podcasts")
async def list_podcasts():
    """Returns a list of all asynchronous audio feedbacks generated by the Passive Listener."""
    import glob
    audio_dir = "frontend/audio"
    os.makedirs(audio_dir, exist_ok=True)
    files = glob.glob(f"{audio_dir}/*.wav") + glob.glob(f"{audio_dir}/*.mp3")
    
    podcasts = []
    for f in sorted(files, key=os.path.getmtime, reverse=True):
        basename = os.path.basename(f)
        podcasts.append({
            "url": f"/static/audio/{basename}",
            "filename": basename,
            "created_at": os.path.getmtime(f)
        })
    return {"podcasts": podcasts}


# Serve the frontend
app.mount("/static", StaticFiles(directory="frontend"), name="static")


@app.get("/")
async def serve_frontend():
    return FileResponse("frontend/stats.html")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
